### ISSUE TITLE
Surface picking often returning too distant atoms

### ISSUE THREAD

**Issue by giagitom** [arose/ngl#328]
Hi, I am trying to pick on the surface and get the closest atom from it.. It seems that often the returned atomProxy is very distant from the picked region (It could be to the opposite edge of the protein for example). Is it normal?

If so, is there a way to get the real picked position coordinates?

**Comment by arose** [comment]
Sadly, the way picking is done this can happen for surfaces. ONe idea to alleviate the problem a bit is to do more coarse picking, that is pick residues or chains instead of atoms for molecular surfaces.

Technical background: Picking is done by rendering the scene with colors representing ids for each atom (or some other entity). For that each vertex is given a id-color. Three vertices form a triangle. The problem arises when a triangle is formed with vertices with different id-colors because then the colors for each pixel in the triangle are are created by interpolation. This behavior can't be switched of in WebGL.

**Comment by giagitom** [comment]
Thanks for the explanation, is it possible to switch on/off only the surface picking?

**Comment by arose** [comment]
I added a parameter `disablePicking` to all representations and enabled it by default for molecular surfaces.

**Comment by tonyyzy** [comment]
@arose 
Is it possible to do a residue level picking based on the exposed surface patch (triangle)?
I can open another issue if it's more appropriate :)

**Comment by arose** [comment]
no, not in NGL (limitation of the rendering engine), but we have this feature in Mol* (molstar.org)

**Comment by tonyyzy** [comment]
Awesome! Looking forward to the day that Mol* takes over and hopefully migrating NGLView to use Mol* backend will be on the timeline ;)
