### ISSUE TITLE
[help wanted] Mouse right click controls like Jmol

### ISSUE THREAD

**Issue by DustBytes** [arose/ngl#447]
Hi
Is it possible to create right click options/menu like jmol/jsmol?
This option is a must for my project.
I can't find any such demo in the examples.

Thank You

**Comment by ppillot** [comment]
This is really difficult to do with current NGL architecture.
In Jmol/Jsmol, one defines a selection and this selection is globably available for subsequent actions regarding representations or coloration (`select protein; cartoon only; color chain`)

In NGL, the focus is on representations for which you can define a selection and different parameters(`component.addRepresentation('cartoon', {seleString: 'protein', colorScheme: 'chainname'}`). One can build a GUI through a system of callbacks triggered by each representation when it's created or updated. This approach is more similar to what softwares such as VMD and Pymol do. It doesn't seem fit to me for creating a context menu "à la" Jmol.

From my own experience with https://libmol.org in order to create a GUI similar to what is feasible with jmol/jsmol I had to create arrays that keep track of which atoms are displayed in each representation chosen by the user, which color schemes are applied to which representation and global variables to store the current selection as well as the currently displayed atoms (to mimic Jmol/Jsmol show/hide command). Feasible, but not straightforward.

**Comment by DustBytes** [comment]
The need of menu is:
some people dont' use full screen, so smaller the area better for them
comparing mutliple strutures is easier with more space
feels native to jmol/jsmol users

**Comment by DustBytes** [comment]
How about this..
A show/hide sidebar with the controls on the view container.
So user can see the structure and let's say on top right, can click on an arrow to show the sidebar, set the options, Apply and gain click on the arrow to hide the sidebar?
Is this possible?

Thank You

**Comment by ppillot** [comment]
Creating a sidebar is as easy to implement as a context menu. That’s not where the difficulty resides. The main challenge is to implement an external state for tracking the user selection, and the selections in each representation, with every edge case. Again, this is feasible on top of NGL but not straightforward for the reasons I stated before, hence it hasn’t been made yet even if I wouldn’t  deny its relevance. 
At present NGL is a visualization library and not a GUI, but it provides a complete API to fuel the bidirectional user interface such as the context menu you are referring to.

**Comment by fredludlow** [comment]
I implemented a selection building extension to Stage to enable picking atoms in different molecules and measuring distances between them (it copies the required atoms to a fake structure that owns the distance repr). (Then there's another class which monitors atom visibility and updates the selection for the fake structure so measurements only appear when both atoms are visible). It feels like a big fudge at the moment but if there are several of us trying to achieve similar things it might make sense to think about how to do it properly, either as part of NGL or a plugin/extension? 

One crazy idea for @arose - allocate all the atom/bond typed arrays etc from a set of huge arrays (each structures AtomStore points to some start/end position in it) so if you want to build a representation containing subsets of different structures you create something like a StructureView referencing discontinuous sections of the underlying array? Not sure how much the extra level of indirection would hurt performance?

**Comment by arose** [comment]
related #480

**Comment by arose** [comment]
closing this as there is no clear action available
