### ISSUE TITLE
Getting the current XYZ for all atoms

### ISSUE THREAD

**Issue by biharck** [arose/ngl#612]
Hi, Guys. 
Is there a way to get the current X Y Z coords for all atoms in runtime?
I mean, let's say I rotated the structure and want to get the current XYZ coordinates for all atoms.

Cheers,

**Comment by fredludlow** [comment]
When you move a molecule (as opposed to just rotating the scene) it updates the component's matrix, rather than the underlying x,y,z coords. You can get both the matrix and the coords and build the effective coordinates from them. 

```javascript
var component = stage.compList[0]   
var m = component.matrix                         // A Matrix4 instance
```
There are lots of different ways to get the atom coordinates (you can use `structure.getAtomProxy` and iterate yourself, or use `eachAtom`), but something like:

```javascript
var effectiveCoords = []

component.structure.eachAtom(function (ap) { 
  var v = new NGL.Vector3(ap.x, ap.y, ap.z)
  v.applyMatrix4(m)
  effectiveCoords.push(v)
})
```
Or something similar depending on what you want the output to look like.

**Comment by biharck** [comment]
Thank you @fredludlow
