### ISSUE TITLE
Problems displaying multiple structures side by side

### ISSUE THREAD

**Issue by ostrokach** [arose/ngl#645]
I'm trying to display 4 structures side-by-side on my website (see codepen [here](https://codepen.io/ostrokach/pen/BEVRgR)).

However, I am running into some problems, particularly with the full-screen feature. No matter which structure is double-clicked, the full-screen window that opens only contains the last structure that was created. When I click "ESC" to exit full-screen mode, the margins around the structure that was displayed are much larger than they where originally.

I'm a new to web development, so sorry if this just me not understanding JavaScript, etc. I am using the latest `ngl` release from the https://unpkg.com/ngl@next CDN.

**Comment by ppillot** [comment]
It's tricky...
In your code, you are looping through the structures and you are declaring a new stage variable at each loop.
But, as your code assign the variable `stage` with a `var` statement in 
```javascript
var stage = new NGL.Stage(`viewport${index}`, {
    backgroundColor: "white"
  });
``` 
then `stage` is global and its value is reassigned after each loop.
You should use `let` instead of `var` so that the `stage` variable is only local to your loop block and doesn't get overwritten at each loop.

As for the fullscreen concern, there is something else in play here. The stage does not get resized horizontally after the fullscreen mode has been escaped. It seems to me that the relative measures for the stage width are involved. With absolute values, the pen behaves as expected: https://codepen.io/anon/pen/XQYxEY

**Comment by ostrokach** [comment]
Thank you for your help @ppillot!

After introducing the changes that you suggest, everything works as expected.
