### ISSUE TITLE
Loading multiple pdb

### ISSUE THREAD

**Issue by drc007** [arose/ngl#661]
I'm working with Open Source Antibiotics consortium (https://github.com/opensourceantibiotics) and I'd like to provide an easy way for people to view crystal structures, docking results, molecular modelling etc.

My first attempt can be seen here.

https://opensourceantibiotics.github.io/murligase/ngl/examples/MurDwebapp.html?script=interactive/MurD_ligand-viewer

The available structures can be chosen by using the dropdown menu in the top left corner. At the moment as each structure is chosen it deletes the previous displayed structure. Is there a way to allow display of multiple structures?

**Comment by fredludlow** [comment]
You can remove the call to stage.removeAllComponents() and change the call to stage.loadFile() to something that tries to find an existing component (to avoid loading the same thing multiple times). e.g. 

```javascript
var _components = {}
function cachedLoad(path, options) {
  if (_components[path] === undefined) {
    _components[path] = stage.loadFile(path, options)
  }
  return _components[path]
}
```
That will return a promise, so you can call `cachedLoad(path).then(function(o) { ... })`

A few issues with the above:
* The UI elements on the left will be reinitialized to default values every time you switch structure (rather than reflecting the real state of that structure). 
* You probably want to listen for components being removed and update the _components object accordingly

**Comment by drc007** [comment]
Thanks. 
Will have to think about UI elements since they probably won't reflect the added structure.

**Comment by fredludlow** [comment]
Closing for now - please reopen if you have further questions on the same issue
