### ISSUE TITLE
Is there a way to create a file object from structure component?

### ISSUE THREAD

**Issue by test-user-18** [arose/ngl#706]
I am creating a web application based on NGL.

http://nglviewer.org/ngl/

I was able to load "PDB" by selecting "File" -> "PDB" and typing PDB ID.

I was able to get a structure component, and I would like to create a file object from it, then pass it to our internal API.

[File - Web APIs | MDN](https://developer.mozilla.org/en-US/docs/Web/API/File)

Is there a way to create a pdb file from structure component?

**Comment by fredludlow** [comment]
You can write files in PDB format with NGL.PdbWriter, but it won't be exactly the same as the input (for example, the header won't be present). 

If that's good enough you can also take the result from the PdbWriter and make a File object
```javascript
var writer = new NGL.PdbWriter(myComponent.structure)
// Plain text:
var data = writer.getData() 
// Or:
var blob = writer.getBlob()
var f = new File([blob], 'filename')
```

If you're not modifying the file at all in NGL, you can also just grab another copy via ajax, wrap it in a File or whatever you need and submit that to your API (if the structure comes from a simple GET then the browser will probably grab it from the cache rather than re-download).

**Comment by test-user-18** [comment]
Thank you for your quick response. I will try your code when I get to work next week. Thank you again.
